@baseUrl = http://localhost:3000

# MESSAGES
GET {{baseUrl}}/messages/
?limit=2
&offset=1
###
GET {{baseUrl}}/messages/7/
###
POST {{baseUrl}}/messages/
Content-Type: application/

  {
    "text": "New message",
    "fromId": 1,
    "toId": 12
  }
###
PATCH {{baseUrl}}/messages/7
Content-Type: application/json

  {
    "text": "Updated message",
    "read": true
  }
###
DELETE  {{baseUrl}}/messages/2
Content-Type: application/json
###

# PERSONS
GET {{baseUrl}}/persons/
###
GET {{baseUrl}}/persons/1/
###
POST {{baseUrl}}/persons/
Content-Type: application/json

{
  "email": "email5@email.com",
  "password": "password",
  "name": "John New"
}
###
PATCH {{baseUrl}}/persons/5
Content-Type: application/json

{
  "password": "123456789",
  "name": "John Doe"
}
###
DELETE  {{baseUrl}}/persons/12
Content-Type: application/json
