@baseUrl = http://localhost:3000

# MESSAGES
GET {{baseUrl}}/messages/
###
GET {{baseUrl}}/messages/1/
###
POST {{baseUrl}}/messages/
Content-Type: application/json

  {
    "text": "New message",
    "from": "John",
    "to": "Joana"
  }
###
PATCH {{baseUrl}}/messages/3
Content-Type: application/json

  {
    "text": "Updated message",
    "read": true
  }
###
DELETE  {{baseUrl}}/messages/2
Content-Type: application/json
###

# PERSONS
GET {{baseUrl}}/persons/
###
GET {{baseUrl}}/persons/1/
###
POST {{baseUrl}}/persons/
Content-Type: application/json

{
  "email": "email4@email.com",
  "password": "password",
  "name": "John2"
}
###
PATCH {{baseUrl}}/persons/5
Content-Type: application/json

{
  "password": "123456789",
  "name": "John Doe"
}
###
DELETE  {{baseUrl}}/persons/11
Content-Type: application/json
