@baseUrl = http://localhost:3000

# MESSAGES
GET {{baseUrl}}/messages/
###
GET {{baseUrl}}/messages/2/
###
POST {{baseUrl}}/messages/
Content-Type: application/json

  {
    "text": "New message",
    "from": "John",
    "to": "Doe",
    "read": false,
    "date": "2025-02-11T19:49:51.410Z"
  }
###
PATCH {{baseUrl}}/messages/2
Content-Type: application/json

  {
    "text": "Updated message 2",
    "from": "John",
    "to": "Doe",
    "read": false,
    "date": "2025-02-11T19:49:51.410Z"
  }
###
DELETE  {{baseUrl}}/messages/1
Content-Type: application/json
